[toolchain]

[features]
resolution = true
skip-lint = false

[programs.Localnet]
token_lottery = "DAkoXJUoFaDS5XuTNCqGcnW9y395aMpA3taJwC9rnRgo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -b --import=tsx -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
